### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by Yao-14** [QIFEIDKN/STAGATE#1]
Hello, I am very interested in your package, and I hope to try your package to process data. But I see that your package requires tensorflow==1.15.0. Is this necessary? Can I use tensorflow==2.7.0

**Comment by RucDongLab** [comment]
Sorry, STAGATE only supports Tensorflow 1.xx currently. You can downgrade it by pip install tensorflow-gpu==1.15.0.

**Comment by Yao-14** [comment]
Thanks.  My CUDA version is 11.3, so can I use the CPU version of tensorflow?I am worried that tensorflow-gpu==1.15.0 cannot be used.

**Comment by forechoandlook** [comment]
> Thanks. My CUDA version is 11.3, so can I use the CPU version of tensorflow?I am worried that tensorflow-gpu==1.15.0 cannot be used.

Actually You can use Colab! This is our reproducation result on Colab https://drive.google.com/drive/folders/1fkZZgXp-lQpWVbQi3HsHuoR3GeSLaGjp. The `reproductation` is the version.
