### ISSUE TITLE
Is there any tutorial of running the single-cell solution ST data? 

### ISSUE THREAD

**Issue by csqray** [QIFEIDKN/STAGATE#12]
Congratulations for this nice work!
I am very interested in running single-cell solution ST data with STAGATE.
I'll appreciate it if you can provide a tutorial of running the single-cell solution ST data.

Thanks!

**Comment by csqray** [comment]
Or can you provide the code running for Fig. S16?

**Comment by RucDongLab** [comment]
We add a Tutorial of the ISH-based STARmap dataset (i.e. the Fig. S16 of the STAGATE paper) at https://stagate.readthedocs.io/en/latest/T9_STARmap.html.

**Comment by csqray** [comment]
Thank you!
