### ISSUE TITLE
problem in applying sc.pp.highly_variable_genes(adata, flavor="seurat_v3", n_top_genes=3000)

### ISSUE THREAD

**Issue by xiao-kong-long** [QIFEIDKN/STAGATE#13]
Any people meet same question?  When I running `sc.pp.highly_variable_genes(adata, flavor="seurat_v3", n_top_genes=3000)`,error occurs.
![image](https://user-images.githubusercontent.com/53474978/188317976-34e27415-4b3a-4db3-96b9-6b1af8bf58c1.png)
what's amazing is I runned it successfully yesterday, but today, when I rerun it, the error occurs. I don't do any modification!!!

**Comment by xiao-kong-long** [comment]
there are some related issue in github in https://github.com/scverse/scanpy/issues/2073

**Comment by RucDongLab** [comment]
In a windows environment, I solved this error by install the "scikit-misc" package by https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-misc.
