### ISSUE TITLE
How to select the best parameter?

### ISSUE THREAD

**Issue by EddieLv** [QIFEIDKN/STAGATE#15]
What a great tool for ST data!
When using STAGATE, I have a question that how to set some hyper-parameters properly?
For example, the [rad_cutoff] in Cal_Spatial_Net().
I found that you set [rad_cutoff] differently in different datasets. And I found that the mean_neighbors are in range 5~10, is it a good standard to set the [rad_cutoff]?

**Comment by RucDongLab** [comment]
Yes, we recommend the mean_neighbors are set in range 5~10, which usually yields good results. But we cannot say that it is the best parameter for every dataset. Fortunately, the effect of this parameter on the result is relatively monotonic, you can try different parameters.

**Comment by EddieLv** [comment]
Thanks for your reply~
