### ISSUE TITLE
Parameter settings

### ISSUE THREAD

**Issue by Yao-14** [QIFEIDKN/STAGATE#2]
Hello, I tested the 3D clustering function in STAGATE with the data of our research group. How should the parameters in STAGATE.Cal_Spatial_Net_3D and STAGATE.train_STAGATE be considered and set reasonably? I am currently using Stereo-seq data.

**Comment by QIFEIDKN** [comment]
Thank you for your consideration about our approach. I think we can further communicate about parameter settings via wechat. My email is dongkangning16@mails.ac.cn.

**Comment by QIFEIDKN** [comment]
Thank you for your consideration about our approach. I think we can further communicate about parameter settings via wechat. My email is dongkangning16@mails.ucas.edu.cn.

**Comment by QIFEIDKN** [comment]
Thank you for your consideration about our approach. I think we can further communicate about parameter settings via wechat. My email is dongkangning16@mails.ucas.ac.cn.

**Comment by Changzhanhe** [comment]
Hi, I also met with the same problem with you. Did you solve this problem yet？
