### ISSUE TITLE
A Promlem when read_visium

### ISSUE THREAD

**Issue by xiao-kong-long** [QIFEIDKN/STAGATE#3]
hello，I meet a problem when run this code:
`adata = sc.read_visium(path=input_dir, count_file=section_id+'_filtered_feature_bc_matrix.h5')`
cause this error as follows:
OSError: ``Data\151676\151676_filtered_feature_bc_matrix.h5`` does not exist
I don't know how can I solve this problem

**Comment by xiao-kong-long** [comment]
I don't know whether the path `Data\151676\151676_filtered_feature_bc_matrix.h5` is wrong?

**Comment by xiao-kong-long** [comment]
I got the answer, I don't create local directory Data, but another problem occurs, could you provide dataset? I can't find csv and json files in this website, I think it's complex for me,  thanks!

**Comment by RucDongLab** [comment]
The spatial information of DLPFC dataset can be found at https://github.com/JinmiaoChenLab/SEDR_analyses/tree/master/data/DLPFC.

**Comment by xiao-kong-long** [comment]
Thanks for you replay! Thanks!
