### ISSUE TITLE
the version of rpy2

### ISSUE THREAD

**Issue by xiao-kong-long** [QIFEIDKN/STAGATE#7]
hello, I wanna ask the version of rpy2 in this project, because when running code, some errors occurs, like this.
![image](https://user-images.githubusercontent.com/53474978/173322232-ca70aec9-1266-49a1-a8b2-f202161e072e.png)

**Comment by xiao-kong-long** [comment]
what's more, I wanna known the version of python

**Comment by dknqifei** [comment]
The version of rpy2 is 3.1.0 in my environment. For convenience, I provide information of all packages in my environment, see https://drive.google.com/file/d/166beudXP5tVCgqs59JDz5OF9hm5m4sWl/view?usp=sharing .

**Comment by xiao-kong-long** [comment]
thanks very much!

**Comment by xiao-kong-long** [comment]
I find that rpy2 3.xx is not support to windows, I want to know if this project must be running on linux? Or other method that makes it run on windows?

**Comment by xiao-kong-long** [comment]
It must run on Linux
