### ISSUE TITLE
Windows or Linux ?

### ISSUE THREAD

**Issue by xiao-kong-long** [QIFEIDKN/STAGATE#8]
I find that rpy2 3.xx is not support to windows, I want to know if this project must be running on linux? Or other method that makes it run on windows?

**Comment by forechoandlook** [comment]
> I find that rpy2 3.xx is not support to windows, I want to know if this project must be running on linux? Or other method that makes it run on windows?

You can use colab, this is my example : https://drive.google.com/drive/folders/1fkZZgXp-lQpWVbQi3HsHuoR3GeSLaGjp

**Comment by xiao-kong-long** [comment]
> > I find that rpy2 3.xx is not support to windows, I want to know if this project must be running on linux? Or other method that makes it run on windows?
> 
> You can use colab, this is my example : https://drive.google.com/drive/folders/1fkZZgXp-lQpWVbQi3HsHuoR3GeSLaGjp

thx, I'll try it.
