### ISSUE TITLE
Problems in PAGA Analysis

### ISSUE THREAD

**Issue by jingjingyac** [QIFEIDKN/STAGATE#9]
Hello, when I run PAGA, sc.tl.paga(used_adata, groups='Ground Truth') got the error ValueError: iterable must yield non-negative integers. I don't know how can I solve this problem.

**Comment by xiao-kong-long** [comment]
I have made some additions and changes on the basis of source code, making it run successfully.
![image](https://user-images.githubusercontent.com/53474978/188080606-44595b57-9ffc-4af2-b012-67986d7fa1cb.png)
On above image, what in red block are additional contents, and changed contents are in green.
Hope it may help you

**Comment by xiao-kong-long** [comment]
pasted codes:
embarked_mapping = {'Layer_1':0, 'Layer_2':1, 'Layer_3':2, 'Layer4':3, 'Layer_5':4, 'Layer_6':5, 'WM':6}

used_adata.obs['Ground Truth'] = used_adata.obs['Ground Truth'].map(embarked_mapping)
used_adata.obs['Ground Truth'] = used_adata.obs['Ground Truth'].fillna(0).astype(int).astype('category')

sc.tl.paga(used_adata, groups='mclust')

**Comment by jingjingyac** [comment]
Ok thanks, I've solved the problem, it might have been the presence of Nan values at the beginning.
